# Generated by Django 5.0 on 2025-03-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_dish_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('В ожидании', 'pending'), ('Готово', 'ready'), ('Оплачено', 'paid')], default='pending', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
